-- 코드를 작성해주세요
SELECT f.ID AS ID, fn.FISH_NAME AS FISH_NAME, f.LENGTH AS LENGTH
FROM FISH_NAME_INFO fn
LEFT JOIN FISH_INFO f ON fn.FISH_TYPE = f.FISH_TYPE
WHERE f.LENGTH = (
    SELECT MAX(f2.LENGTH)
    FROM FISH_INFO f2
    WHERE f.FISH_TYPE = f2.FISH_TYPE
);